import type { PortEntry } from "./types";

const now = Math.floor(Date.now() / 1000);

export const MOCK_PORTS: PortEntry[] = [
  {
    port: 3000,
    pid: 4101,
    processName: "node",
    command: "node /Users/dev/tapuy/node_modules/.bin/next dev",
    cwd: "~/dev/tapuy/apps/web",
    project: "tapuy-web",
    label: "Next.js dev",
    user: "dev",
    startedAt: now - 12 * 60,
    memoryBytes: 210 * 1024 * 1024,
    killable: true,
  },
  {
    port: 5173,
    pid: 4102,
    processName: "node",
    command: "node /Users/dev/laqi/panel/node_modules/.bin/vite --host",
    cwd: "~/dev/laqi/panel-with-a-very-long-directory-name/apps/dashboard",
    project: "laqi-panel",
    label: "Vite",
    user: "dev",
    startedAt: now - 2 * 3600,
    memoryBytes: 95 * 1024 * 1024,
    killable: true,
  },
  {
    port: 5432,
    pid: 312,
    processName: "postgres",
    command: "/opt/homebrew/bin/postgres -D /opt/homebrew/var/postgresql@16",
    cwd: null,
    project: null,
    label: "PostgreSQL",
    user: "dev",
    startedAt: now - 3 * 86400,
    memoryBytes: 48 * 1024 * 1024,
    killable: true,
  },
  {
    port: 7000,
    pid: 88,
    processName: "ControlCenter",
    command: "/System/Library/CoreServices/ControlCenter.app/Contents/MacOS/ControlCenter",
    cwd: null,
    project: null,
    label: "ControlCenter",
    user: "root",
    startedAt: now - 5 * 86400,
    memoryBytes: 30 * 1024 * 1024,
    killable: false,
  },
  {
    port: 8787,
    pid: 4103,
    processName: "workerd",
    command: "/Users/dev/niway/api/node_modules/.bin/workerd serve",
    cwd: "~/dev/niway/api",
    project: "niway-api",
    label: "Wrangler (Workers)",
    user: "dev",
    startedAt: now - 40 * 60,
    memoryBytes: 130 * 1024 * 1024,
    killable: true,
  },
];
